// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSysUserGroupMapping = "sys_user_group_mapping"

// SysUserGroupMapping mapped from table <sys_user_group_mapping>
type SysUserGroupMapping struct {
	GroupID int64 `gorm:"column:group_id;primaryKey;comment:用户组 ID" json:"group_id"` // 用户组 ID
	UserID  int64 `gorm:"column:user_id;primaryKey;comment:用户 ID" json:"user_id"`    // 用户 ID
}

// TableName SysUserGroupMapping's table name
func (*SysUserGroupMapping) TableName() string {
	return TableNameSysUserGroupMapping
}
