// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysRoleIDScope = "sys_role_id_scope"

// SysRoleIDScope mapped from table <sys_role_id_scope>
type SysRoleIDScope struct {
	ID        int64          `gorm:"column:id;primaryKey;comment:主键 ID" json:"id"`                                        // 主键 ID
	Status    int16          `gorm:"column:status;not null;default:1;comment:数据状态，0：禁用、1：启用" json:"status"`               // 数据状态，0：禁用、1：启用
	Type      int16          `gorm:"column:type;not null;default:1;comment:数据 ID 类型，1：用户ID、2：部门ID、3：用户组ID" json:"type"`   // 数据 ID 类型，1：用户ID、2：部门ID、3：用户组ID
	RoleID    int64          `gorm:"column:role_id;not null;comment:角色 ID" json:"role_id"`                                // 角色 ID
	DataID    int64          `gorm:"column:data_id;not null;comment:数据 ID" json:"data_id"`                                // 数据 ID
	CreatedBy int64          `gorm:"column:created_by;not null;comment:创建人" json:"created_by"`                            // 创建人
	CreatedAt time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedBy int64          `gorm:"column:updated_by;not null;comment:更新人" json:"updated_by"`                            // 更新人
	UpdatedAt time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;default:NULL;comment:删除时间" json:"deleted_at"`                       // 删除时间
	TenantID  string         `gorm:"column:tenant_id;not null;comment:租户 ID" json:"tenant_id"`                            // 租户 ID
}

// TableName SysRoleIDScope's table name
func (*SysRoleIDScope) TableName() string {
	return TableNameSysRoleIDScope
}
