// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSysDeptClosure = "sys_dept_closure"

// SysDeptClosure mapped from table <sys_dept_closure>
type SysDeptClosure struct {
	ID           int64 `gorm:"column:id;not null" json:"id"`
	AncestorID   int64 `gorm:"column:ancestor_id;primaryKey;comment:祖先节点ID" json:"ancestor_id"`             // 祖先节点ID
	DescendantID int64 `gorm:"column:descendant_id;primaryKey;comment:后代节点ID" json:"descendant_id"`         // 后代节点ID
	Depth        int32 `gorm:"column:depth;not null;comment:深度/距离（0表示自身，1表示直接子节点，2表示孙子节点...）" json:"depth"` // 深度/距离（0表示自身，1表示直接子节点，2表示孙子节点...）
}

// TableName SysDeptClosure's table name
func (*SysDeptClosure) TableName() string {
	return TableNameSysDeptClosure
}
