// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysUser = "sys_user"

// SysUser mapped from table <sys_user>
type SysUser struct {
	ID               int64          `gorm:"column:id;primaryKey;comment:用户 ID" json:"id"`                                        // 用户 ID
	Status           int16          `gorm:"column:status;not null;default:1;comment:数据状态，0：禁用、1：启用" json:"status"`               // 数据状态，0：禁用、1：启用
	CreatedBy        int64          `gorm:"column:created_by;not null;comment:创建人" json:"created_by"`                            // 创建人
	CreatedAt        time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedBy        int64          `gorm:"column:updated_by;not null;comment:更新人" json:"updated_by"`                            // 更新人
	UpdatedAt        time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt        gorm.DeletedAt `gorm:"column:deleted_at;default:NULL;comment:删除时间" json:"deleted_at"`                       // 删除时间
	TenantID         string         `gorm:"column:tenant_id;comment:租户 ID" json:"tenant_id"`                                     // 租户 ID
	OwnerUserID      int64          `gorm:"column:owner_user_id;comment:归属用户 ID" json:"owner_user_id"`                           // 归属用户 ID
	OwnerDeptID      int64          `gorm:"column:owner_dept_id;comment:归属部门 ID" json:"owner_dept_id"`                           // 归属部门 ID
	OwnerUserGroupID int64          `gorm:"column:owner_user_group_id;comment:归属用户组 ID" json:"owner_user_group_id"`              // 归属用户组 ID
	Name             string         `gorm:"column:name;not null;comment:用户名" json:"name"`                                        // 用户名
	Nickname         string         `gorm:"column:nickname;not null;comment:昵称" json:"nickname"`                                 // 昵称
	Password         string         `gorm:"column:password;not null;comment:密码" json:"password"`                                 // 密码
	Remark           string         `gorm:"column:remark;comment:备注" json:"remark"`                                              // 备注
}

// TableName SysUser's table name
func (*SysUser) TableName() string {
	return TableNameSysUser
}
