// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysDept = "sys_dept"

// SysDept mapped from table <sys_dept>
type SysDept struct {
	ID               int64          `gorm:"column:id;primaryKey;comment:部门 ID" json:"id"`                                        // 部门 ID
	Status           int16          `gorm:"column:status;not null;default:1;comment:数据状态，0：禁用、1：启用" json:"status"`               // 数据状态，0：禁用、1：启用
	CreatedBy        int64          `gorm:"column:created_by;not null;comment:创建人" json:"created_by"`                            // 创建人
	CreatedAt        time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedBy        int64          `gorm:"column:updated_by;not null;comment:更新人" json:"updated_by"`                            // 更新人
	UpdatedAt        time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新人" json:"updated_at"`  // 更新人
	DeletedAt        gorm.DeletedAt `gorm:"column:deleted_at;default:NULL;comment:删除时间" json:"deleted_at"`                       // 删除时间
	TenantID         string         `gorm:"column:tenant_id;not null;comment:租户 ID" json:"tenant_id"`                            // 租户 ID
	ParentID         int64          `gorm:"column:parent_id;comment:父级部门 ID" json:"parent_id"`                                   // 父级部门 ID
	Name             string         `gorm:"column:name;not null;comment:部门名" json:"name"`                                        // 部门名
	OwnerUserID      int64          `gorm:"column:owner_user_id;not null;comment:部门管理员用户" json:"owner_user_id"`                  // 部门管理员用户
	OwnerUserGroupID int64          `gorm:"column:owner_user_group_id;comment:归属用户组 ID" json:"owner_user_group_id"`              // 归属用户组 ID
}

// TableName SysDept's table name
func (*SysDept) TableName() string {
	return TableNameSysDept
}
