// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysRole = "sys_role"

// SysRole mapped from table <sys_role>
type SysRole struct {
	ID          int64          `gorm:"column:id;primaryKey;comment:主键 ID" json:"id"`                                                                         // 主键 ID
	Status      int16          `gorm:"column:status;not null;default:1;comment:数据状态，0：禁用、1：启用" json:"status"`                                                // 数据状态，0：禁用、1：启用
	CreatedBy   int64          `gorm:"column:created_by;not null;comment:创建人" json:"created_by"`                                                             // 创建人
	CreatedAt   time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`                                  // 创建时间
	UpdatedBy   int64          `gorm:"column:updated_by;not null;comment:更新人" json:"updated_by"`                                                             // 更新人
	UpdatedAt   time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`                                  // 更新时间
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;default:NULL;comment:删除时间" json:"deleted_at"`                                                        // 删除时间
	TenantID    string         `gorm:"column:tenant_id;not null;comment:租户 ID" json:"tenant_id"`                                                             // 租户 ID
	Name        string         `gorm:"column:name;not null;comment:角色名" json:"name"`                                                                         // 角色名
	Code        string         `gorm:"column:code;not null;comment:权限编码" json:"code"`                                                                        // 权限编码
	RoleType    int16          `gorm:"column:role_type;not null;default:2;comment:角色类型：1-系统预置(不可删除，核心权限不可剥离) 2-租户自定义" json:"role_type"`                      // 角色类型：1-系统预置(不可删除，核心权限不可剥离) 2-租户自定义
	DataScope   int16          `gorm:"column:data_scope;not null;default:1;comment:数据范围规则：1-仅本人 2-本部门 3-本部门及子部门 4-指定人 5-指定部门 6-全租户 7-用户组" json:"data_scope"` // 数据范围规则：1-仅本人 2-本部门 3-本部门及子部门 4-指定人 5-指定部门 6-全租户 7-用户组
	ScopeDeptID int64          `gorm:"column:scope_dept_id;comment:组织可见范围：限定角色可分配的部门层级。NULL=全租户可分配，具体部门ID=仅该部门及子部门可分配" json:"scope_dept_id"`                 // 组织可见范围：限定角色可分配的部门层级。NULL=全租户可分配，具体部门ID=仅该部门及子部门可分配
	Remark      string         `gorm:"column:remark;comment:备注" json:"remark"`                                                                               // 备注
}

// TableName SysRole's table name
func (*SysRole) TableName() string {
	return TableNameSysRole
}
