// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserRoleMapping = "user_role_mapping"

// UserRoleMapping mapped from table <user_role_mapping>
type UserRoleMapping struct {
	UserID int64 `gorm:"column:user_id;primaryKey;comment:用户 ID" json:"user_id"` // 用户 ID
	RoleID int64 `gorm:"column:role_id;primaryKey;comment:角色 ID" json:"role_id"` // 角色 ID
}

// TableName UserRoleMapping's table name
func (*UserRoleMapping) TableName() string {
	return TableNameUserRoleMapping
}
