// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"go_orm_tt/internal/model"
)

func newBasic(db *gorm.DB, opts ...gen.DOOption) basic {
	_basic := basic{}

	_basic.basicDo.UseDB(db, opts...)
	_basic.basicDo.UseModel(&model.Basic{})

	tableName := _basic.basicDo.TableName()
	_basic.ALL = field.NewAsterisk(tableName)
	_basic.ID = field.NewInt64(tableName, "id")
	_basic.Status = field.NewInt16(tableName, "status")
	_basic.CreatedBy = field.NewInt64(tableName, "created_by")
	_basic.CreatedAt = field.NewTime(tableName, "created_at")
	_basic.UpdatedBy = field.NewInt64(tableName, "updated_by")
	_basic.UpdatedAt = field.NewTime(tableName, "updated_at")
	_basic.DeletedAt = field.NewField(tableName, "deleted_at")
	_basic.TenantID = field.NewString(tableName, "tenant_id")
	_basic.OwnerUserID = field.NewInt64(tableName, "owner_user_id")
	_basic.OwnerDeptID = field.NewInt64(tableName, "owner_dept_id")
	_basic.OwnerUserGroupID = field.NewInt64(tableName, "owner_user_group_id")

	_basic.fillFieldMap()

	return _basic
}

type basic struct {
	basicDo

	ALL              field.Asterisk
	ID               field.Int64  // 主键 ID
	Status           field.Int16  // 数据状态，0：禁用、1：启用
	CreatedBy        field.Int64  // 创建人
	CreatedAt        field.Time   // 创建时间
	UpdatedBy        field.Int64  // 更新人
	UpdatedAt        field.Time   // 更新时间
	DeletedAt        field.Field  // 删除时间
	TenantID         field.String // 租户 ID
	OwnerUserID      field.Int64  // 归属用户 ID
	OwnerDeptID      field.Int64  // 归属部门 ID
	OwnerUserGroupID field.Int64  // 归属用户组 ID

	fieldMap map[string]field.Expr
}

func (b basic) Table(newTableName string) *basic {
	b.basicDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b basic) As(alias string) *basic {
	b.basicDo.DO = *(b.basicDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *basic) updateTableName(table string) *basic {
	b.ALL = field.NewAsterisk(table)
	b.ID = field.NewInt64(table, "id")
	b.Status = field.NewInt16(table, "status")
	b.CreatedBy = field.NewInt64(table, "created_by")
	b.CreatedAt = field.NewTime(table, "created_at")
	b.UpdatedBy = field.NewInt64(table, "updated_by")
	b.UpdatedAt = field.NewTime(table, "updated_at")
	b.DeletedAt = field.NewField(table, "deleted_at")
	b.TenantID = field.NewString(table, "tenant_id")
	b.OwnerUserID = field.NewInt64(table, "owner_user_id")
	b.OwnerDeptID = field.NewInt64(table, "owner_dept_id")
	b.OwnerUserGroupID = field.NewInt64(table, "owner_user_group_id")

	b.fillFieldMap()

	return b
}

func (b *basic) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *basic) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 11)
	b.fieldMap["id"] = b.ID
	b.fieldMap["status"] = b.Status
	b.fieldMap["created_by"] = b.CreatedBy
	b.fieldMap["created_at"] = b.CreatedAt
	b.fieldMap["updated_by"] = b.UpdatedBy
	b.fieldMap["updated_at"] = b.UpdatedAt
	b.fieldMap["deleted_at"] = b.DeletedAt
	b.fieldMap["tenant_id"] = b.TenantID
	b.fieldMap["owner_user_id"] = b.OwnerUserID
	b.fieldMap["owner_dept_id"] = b.OwnerDeptID
	b.fieldMap["owner_user_group_id"] = b.OwnerUserGroupID
}

func (b basic) clone(db *gorm.DB) basic {
	b.basicDo.ReplaceConnPool(db.Statement.ConnPool)
	return b
}

func (b basic) replaceDB(db *gorm.DB) basic {
	b.basicDo.ReplaceDB(db)
	return b
}

type basicDo struct{ gen.DO }

type IBasicDo interface {
	gen.SubQuery
	Debug() IBasicDo
	WithContext(ctx context.Context) IBasicDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IBasicDo
	WriteDB() IBasicDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IBasicDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IBasicDo
	Not(conds ...gen.Condition) IBasicDo
	Or(conds ...gen.Condition) IBasicDo
	Select(conds ...field.Expr) IBasicDo
	Where(conds ...gen.Condition) IBasicDo
	Order(conds ...field.Expr) IBasicDo
	Distinct(cols ...field.Expr) IBasicDo
	Omit(cols ...field.Expr) IBasicDo
	Join(table schema.Tabler, on ...field.Expr) IBasicDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IBasicDo
	RightJoin(table schema.Tabler, on ...field.Expr) IBasicDo
	Group(cols ...field.Expr) IBasicDo
	Having(conds ...gen.Condition) IBasicDo
	Limit(limit int) IBasicDo
	Offset(offset int) IBasicDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IBasicDo
	Unscoped() IBasicDo
	Create(values ...*model.Basic) error
	CreateInBatches(values []*model.Basic, batchSize int) error
	Save(values ...*model.Basic) error
	First() (*model.Basic, error)
	Take() (*model.Basic, error)
	Last() (*model.Basic, error)
	Find() ([]*model.Basic, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Basic, err error)
	FindInBatches(result *[]*model.Basic, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Basic) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IBasicDo
	Assign(attrs ...field.AssignExpr) IBasicDo
	Joins(fields ...field.RelationField) IBasicDo
	Preload(fields ...field.RelationField) IBasicDo
	FirstOrInit() (*model.Basic, error)
	FirstOrCreate() (*model.Basic, error)
	FindByPage(offset int, limit int) (result []*model.Basic, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IBasicDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (b basicDo) Debug() IBasicDo {
	return b.withDO(b.DO.Debug())
}

func (b basicDo) WithContext(ctx context.Context) IBasicDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b basicDo) ReadDB() IBasicDo {
	return b.Clauses(dbresolver.Read)
}

func (b basicDo) WriteDB() IBasicDo {
	return b.Clauses(dbresolver.Write)
}

func (b basicDo) Session(config *gorm.Session) IBasicDo {
	return b.withDO(b.DO.Session(config))
}

func (b basicDo) Clauses(conds ...clause.Expression) IBasicDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b basicDo) Returning(value interface{}, columns ...string) IBasicDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b basicDo) Not(conds ...gen.Condition) IBasicDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b basicDo) Or(conds ...gen.Condition) IBasicDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b basicDo) Select(conds ...field.Expr) IBasicDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b basicDo) Where(conds ...gen.Condition) IBasicDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b basicDo) Order(conds ...field.Expr) IBasicDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b basicDo) Distinct(cols ...field.Expr) IBasicDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b basicDo) Omit(cols ...field.Expr) IBasicDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b basicDo) Join(table schema.Tabler, on ...field.Expr) IBasicDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b basicDo) LeftJoin(table schema.Tabler, on ...field.Expr) IBasicDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b basicDo) RightJoin(table schema.Tabler, on ...field.Expr) IBasicDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b basicDo) Group(cols ...field.Expr) IBasicDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b basicDo) Having(conds ...gen.Condition) IBasicDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b basicDo) Limit(limit int) IBasicDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b basicDo) Offset(offset int) IBasicDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b basicDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IBasicDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b basicDo) Unscoped() IBasicDo {
	return b.withDO(b.DO.Unscoped())
}

func (b basicDo) Create(values ...*model.Basic) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b basicDo) CreateInBatches(values []*model.Basic, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b basicDo) Save(values ...*model.Basic) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b basicDo) First() (*model.Basic, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Basic), nil
	}
}

func (b basicDo) Take() (*model.Basic, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Basic), nil
	}
}

func (b basicDo) Last() (*model.Basic, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Basic), nil
	}
}

func (b basicDo) Find() ([]*model.Basic, error) {
	result, err := b.DO.Find()
	return result.([]*model.Basic), err
}

func (b basicDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Basic, err error) {
	buf := make([]*model.Basic, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b basicDo) FindInBatches(result *[]*model.Basic, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b basicDo) Attrs(attrs ...field.AssignExpr) IBasicDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b basicDo) Assign(attrs ...field.AssignExpr) IBasicDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b basicDo) Joins(fields ...field.RelationField) IBasicDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b basicDo) Preload(fields ...field.RelationField) IBasicDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b basicDo) FirstOrInit() (*model.Basic, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Basic), nil
	}
}

func (b basicDo) FirstOrCreate() (*model.Basic, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Basic), nil
	}
}

func (b basicDo) FindByPage(offset int, limit int) (result []*model.Basic, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b basicDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b basicDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b basicDo) Delete(models ...*model.Basic) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *basicDo) withDO(do gen.Dao) *basicDo {
	b.DO = *do.(*gen.DO)
	return b
}
