// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                   = new(Query)
	Basic               *basic
	SysDept             *sysDept
	SysDeptClosure      *sysDeptClosure
	SysRole             *sysRole
	SysRoleIDScope      *sysRoleIDScope
	SysTenant           *sysTenant
	SysUser             *sysUser
	SysUserGroup        *sysUserGroup
	SysUserGroupMapping *sysUserGroupMapping
	UserRoleMapping     *userRoleMapping
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Basic = &Q.Basic
	SysDept = &Q.SysDept
	SysDeptClosure = &Q.SysDeptClosure
	SysRole = &Q.SysRole
	SysRoleIDScope = &Q.SysRoleIDScope
	SysTenant = &Q.SysTenant
	SysUser = &Q.SysUser
	SysUserGroup = &Q.SysUserGroup
	SysUserGroupMapping = &Q.SysUserGroupMapping
	UserRoleMapping = &Q.UserRoleMapping
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                  db,
		Basic:               newBasic(db, opts...),
		SysDept:             newSysDept(db, opts...),
		SysDeptClosure:      newSysDeptClosure(db, opts...),
		SysRole:             newSysRole(db, opts...),
		SysRoleIDScope:      newSysRoleIDScope(db, opts...),
		SysTenant:           newSysTenant(db, opts...),
		SysUser:             newSysUser(db, opts...),
		SysUserGroup:        newSysUserGroup(db, opts...),
		SysUserGroupMapping: newSysUserGroupMapping(db, opts...),
		UserRoleMapping:     newUserRoleMapping(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Basic               basic
	SysDept             sysDept
	SysDeptClosure      sysDeptClosure
	SysRole             sysRole
	SysRoleIDScope      sysRoleIDScope
	SysTenant           sysTenant
	SysUser             sysUser
	SysUserGroup        sysUserGroup
	SysUserGroupMapping sysUserGroupMapping
	UserRoleMapping     userRoleMapping
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) UnderlyingDB() *gorm.DB { return q.db }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                  db,
		Basic:               q.Basic.clone(db),
		SysDept:             q.SysDept.clone(db),
		SysDeptClosure:      q.SysDeptClosure.clone(db),
		SysRole:             q.SysRole.clone(db),
		SysRoleIDScope:      q.SysRoleIDScope.clone(db),
		SysTenant:           q.SysTenant.clone(db),
		SysUser:             q.SysUser.clone(db),
		SysUserGroup:        q.SysUserGroup.clone(db),
		SysUserGroupMapping: q.SysUserGroupMapping.clone(db),
		UserRoleMapping:     q.UserRoleMapping.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                  db,
		Basic:               q.Basic.replaceDB(db),
		SysDept:             q.SysDept.replaceDB(db),
		SysDeptClosure:      q.SysDeptClosure.replaceDB(db),
		SysRole:             q.SysRole.replaceDB(db),
		SysRoleIDScope:      q.SysRoleIDScope.replaceDB(db),
		SysTenant:           q.SysTenant.replaceDB(db),
		SysUser:             q.SysUser.replaceDB(db),
		SysUserGroup:        q.SysUserGroup.replaceDB(db),
		SysUserGroupMapping: q.SysUserGroupMapping.replaceDB(db),
		UserRoleMapping:     q.UserRoleMapping.replaceDB(db),
	}
}

type queryCtx struct {
	Basic               IBasicDo
	SysDept             ISysDeptDo
	SysDeptClosure      ISysDeptClosureDo
	SysRole             ISysRoleDo
	SysRoleIDScope      ISysRoleIDScopeDo
	SysTenant           ISysTenantDo
	SysUser             ISysUserDo
	SysUserGroup        ISysUserGroupDo
	SysUserGroupMapping ISysUserGroupMappingDo
	UserRoleMapping     IUserRoleMappingDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Basic:               q.Basic.WithContext(ctx),
		SysDept:             q.SysDept.WithContext(ctx),
		SysDeptClosure:      q.SysDeptClosure.WithContext(ctx),
		SysRole:             q.SysRole.WithContext(ctx),
		SysRoleIDScope:      q.SysRoleIDScope.WithContext(ctx),
		SysTenant:           q.SysTenant.WithContext(ctx),
		SysUser:             q.SysUser.WithContext(ctx),
		SysUserGroup:        q.SysUserGroup.WithContext(ctx),
		SysUserGroupMapping: q.SysUserGroupMapping.WithContext(ctx),
		UserRoleMapping:     q.UserRoleMapping.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
