// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"go_orm_tt/internal/model"
)

func newSysUserGroup(db *gorm.DB, opts ...gen.DOOption) sysUserGroup {
	_sysUserGroup := sysUserGroup{}

	_sysUserGroup.sysUserGroupDo.UseDB(db, opts...)
	_sysUserGroup.sysUserGroupDo.UseModel(&model.SysUserGroup{})

	tableName := _sysUserGroup.sysUserGroupDo.TableName()
	_sysUserGroup.ALL = field.NewAsterisk(tableName)
	_sysUserGroup.ID = field.NewInt64(tableName, "id")
	_sysUserGroup.Status = field.NewInt16(tableName, "status")
	_sysUserGroup.CreatedBy = field.NewInt64(tableName, "created_by")
	_sysUserGroup.CreatedAt = field.NewTime(tableName, "created_at")
	_sysUserGroup.UpdatedBy = field.NewInt64(tableName, "updated_by")
	_sysUserGroup.UpdatedAt = field.NewTime(tableName, "updated_at")
	_sysUserGroup.DeletedAt = field.NewField(tableName, "deleted_at")
	_sysUserGroup.TenantID = field.NewString(tableName, "tenant_id")
	_sysUserGroup.Name = field.NewString(tableName, "name")
	_sysUserGroup.Code = field.NewString(tableName, "code")
	_sysUserGroup.OwnerUserID = field.NewInt64(tableName, "owner_user_id")
	_sysUserGroup.Remark = field.NewString(tableName, "remark")

	_sysUserGroup.fillFieldMap()

	return _sysUserGroup
}

type sysUserGroup struct {
	sysUserGroupDo

	ALL         field.Asterisk
	ID          field.Int64  // 用户组 ID
	Status      field.Int16  // 数据状态，0：禁用、1：启用
	CreatedBy   field.Int64  // 创建人
	CreatedAt   field.Time   // 创建时间
	UpdatedBy   field.Int64  // 更新人
	UpdatedAt   field.Time   // 更新时间
	DeletedAt   field.Field  // 删除时间
	TenantID    field.String // 租户 ID
	Name        field.String // 组名
	Code        field.String // 组编码
	OwnerUserID field.Int64  // 组长/归属用户
	Remark      field.String // 备注

	fieldMap map[string]field.Expr
}

func (s sysUserGroup) Table(newTableName string) *sysUserGroup {
	s.sysUserGroupDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysUserGroup) As(alias string) *sysUserGroup {
	s.sysUserGroupDo.DO = *(s.sysUserGroupDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysUserGroup) updateTableName(table string) *sysUserGroup {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.Status = field.NewInt16(table, "status")
	s.CreatedBy = field.NewInt64(table, "created_by")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedBy = field.NewInt64(table, "updated_by")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.DeletedAt = field.NewField(table, "deleted_at")
	s.TenantID = field.NewString(table, "tenant_id")
	s.Name = field.NewString(table, "name")
	s.Code = field.NewString(table, "code")
	s.OwnerUserID = field.NewInt64(table, "owner_user_id")
	s.Remark = field.NewString(table, "remark")

	s.fillFieldMap()

	return s
}

func (s *sysUserGroup) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysUserGroup) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 12)
	s.fieldMap["id"] = s.ID
	s.fieldMap["status"] = s.Status
	s.fieldMap["created_by"] = s.CreatedBy
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_by"] = s.UpdatedBy
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["deleted_at"] = s.DeletedAt
	s.fieldMap["tenant_id"] = s.TenantID
	s.fieldMap["name"] = s.Name
	s.fieldMap["code"] = s.Code
	s.fieldMap["owner_user_id"] = s.OwnerUserID
	s.fieldMap["remark"] = s.Remark
}

func (s sysUserGroup) clone(db *gorm.DB) sysUserGroup {
	s.sysUserGroupDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysUserGroup) replaceDB(db *gorm.DB) sysUserGroup {
	s.sysUserGroupDo.ReplaceDB(db)
	return s
}

type sysUserGroupDo struct{ gen.DO }

type ISysUserGroupDo interface {
	gen.SubQuery
	Debug() ISysUserGroupDo
	WithContext(ctx context.Context) ISysUserGroupDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysUserGroupDo
	WriteDB() ISysUserGroupDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysUserGroupDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysUserGroupDo
	Not(conds ...gen.Condition) ISysUserGroupDo
	Or(conds ...gen.Condition) ISysUserGroupDo
	Select(conds ...field.Expr) ISysUserGroupDo
	Where(conds ...gen.Condition) ISysUserGroupDo
	Order(conds ...field.Expr) ISysUserGroupDo
	Distinct(cols ...field.Expr) ISysUserGroupDo
	Omit(cols ...field.Expr) ISysUserGroupDo
	Join(table schema.Tabler, on ...field.Expr) ISysUserGroupDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysUserGroupDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysUserGroupDo
	Group(cols ...field.Expr) ISysUserGroupDo
	Having(conds ...gen.Condition) ISysUserGroupDo
	Limit(limit int) ISysUserGroupDo
	Offset(offset int) ISysUserGroupDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysUserGroupDo
	Unscoped() ISysUserGroupDo
	Create(values ...*model.SysUserGroup) error
	CreateInBatches(values []*model.SysUserGroup, batchSize int) error
	Save(values ...*model.SysUserGroup) error
	First() (*model.SysUserGroup, error)
	Take() (*model.SysUserGroup, error)
	Last() (*model.SysUserGroup, error)
	Find() ([]*model.SysUserGroup, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysUserGroup, err error)
	FindInBatches(result *[]*model.SysUserGroup, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SysUserGroup) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysUserGroupDo
	Assign(attrs ...field.AssignExpr) ISysUserGroupDo
	Joins(fields ...field.RelationField) ISysUserGroupDo
	Preload(fields ...field.RelationField) ISysUserGroupDo
	FirstOrInit() (*model.SysUserGroup, error)
	FirstOrCreate() (*model.SysUserGroup, error)
	FindByPage(offset int, limit int) (result []*model.SysUserGroup, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysUserGroupDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysUserGroupDo) Debug() ISysUserGroupDo {
	return s.withDO(s.DO.Debug())
}

func (s sysUserGroupDo) WithContext(ctx context.Context) ISysUserGroupDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysUserGroupDo) ReadDB() ISysUserGroupDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysUserGroupDo) WriteDB() ISysUserGroupDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysUserGroupDo) Session(config *gorm.Session) ISysUserGroupDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysUserGroupDo) Clauses(conds ...clause.Expression) ISysUserGroupDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysUserGroupDo) Returning(value interface{}, columns ...string) ISysUserGroupDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysUserGroupDo) Not(conds ...gen.Condition) ISysUserGroupDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysUserGroupDo) Or(conds ...gen.Condition) ISysUserGroupDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysUserGroupDo) Select(conds ...field.Expr) ISysUserGroupDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysUserGroupDo) Where(conds ...gen.Condition) ISysUserGroupDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysUserGroupDo) Order(conds ...field.Expr) ISysUserGroupDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysUserGroupDo) Distinct(cols ...field.Expr) ISysUserGroupDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysUserGroupDo) Omit(cols ...field.Expr) ISysUserGroupDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysUserGroupDo) Join(table schema.Tabler, on ...field.Expr) ISysUserGroupDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysUserGroupDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysUserGroupDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysUserGroupDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysUserGroupDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysUserGroupDo) Group(cols ...field.Expr) ISysUserGroupDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysUserGroupDo) Having(conds ...gen.Condition) ISysUserGroupDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysUserGroupDo) Limit(limit int) ISysUserGroupDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysUserGroupDo) Offset(offset int) ISysUserGroupDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysUserGroupDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysUserGroupDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysUserGroupDo) Unscoped() ISysUserGroupDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysUserGroupDo) Create(values ...*model.SysUserGroup) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysUserGroupDo) CreateInBatches(values []*model.SysUserGroup, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysUserGroupDo) Save(values ...*model.SysUserGroup) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysUserGroupDo) First() (*model.SysUserGroup, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysUserGroup), nil
	}
}

func (s sysUserGroupDo) Take() (*model.SysUserGroup, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysUserGroup), nil
	}
}

func (s sysUserGroupDo) Last() (*model.SysUserGroup, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysUserGroup), nil
	}
}

func (s sysUserGroupDo) Find() ([]*model.SysUserGroup, error) {
	result, err := s.DO.Find()
	return result.([]*model.SysUserGroup), err
}

func (s sysUserGroupDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysUserGroup, err error) {
	buf := make([]*model.SysUserGroup, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysUserGroupDo) FindInBatches(result *[]*model.SysUserGroup, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysUserGroupDo) Attrs(attrs ...field.AssignExpr) ISysUserGroupDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysUserGroupDo) Assign(attrs ...field.AssignExpr) ISysUserGroupDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysUserGroupDo) Joins(fields ...field.RelationField) ISysUserGroupDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysUserGroupDo) Preload(fields ...field.RelationField) ISysUserGroupDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysUserGroupDo) FirstOrInit() (*model.SysUserGroup, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysUserGroup), nil
	}
}

func (s sysUserGroupDo) FirstOrCreate() (*model.SysUserGroup, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysUserGroup), nil
	}
}

func (s sysUserGroupDo) FindByPage(offset int, limit int) (result []*model.SysUserGroup, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysUserGroupDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysUserGroupDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysUserGroupDo) Delete(models ...*model.SysUserGroup) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysUserGroupDo) withDO(do gen.Dao) *sysUserGroupDo {
	s.DO = *do.(*gen.DO)
	return s
}
