// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"go_orm_tt/internal/model"
)

func newSysRoleIDScope(db *gorm.DB, opts ...gen.DOOption) sysRoleIDScope {
	_sysRoleIDScope := sysRoleIDScope{}

	_sysRoleIDScope.sysRoleIDScopeDo.UseDB(db, opts...)
	_sysRoleIDScope.sysRoleIDScopeDo.UseModel(&model.SysRoleIDScope{})

	tableName := _sysRoleIDScope.sysRoleIDScopeDo.TableName()
	_sysRoleIDScope.ALL = field.NewAsterisk(tableName)
	_sysRoleIDScope.ID = field.NewInt64(tableName, "id")
	_sysRoleIDScope.Status = field.NewInt16(tableName, "status")
	_sysRoleIDScope.Type = field.NewInt16(tableName, "type")
	_sysRoleIDScope.RoleID = field.NewInt64(tableName, "role_id")
	_sysRoleIDScope.DataID = field.NewInt64(tableName, "data_id")
	_sysRoleIDScope.CreatedBy = field.NewInt64(tableName, "created_by")
	_sysRoleIDScope.CreatedAt = field.NewTime(tableName, "created_at")
	_sysRoleIDScope.UpdatedBy = field.NewInt64(tableName, "updated_by")
	_sysRoleIDScope.UpdatedAt = field.NewTime(tableName, "updated_at")
	_sysRoleIDScope.DeletedAt = field.NewField(tableName, "deleted_at")
	_sysRoleIDScope.TenantID = field.NewString(tableName, "tenant_id")

	_sysRoleIDScope.fillFieldMap()

	return _sysRoleIDScope
}

type sysRoleIDScope struct {
	sysRoleIDScopeDo

	ALL       field.Asterisk
	ID        field.Int64  // 主键 ID
	Status    field.Int16  // 数据状态，0：禁用、1：启用
	Type      field.Int16  // 数据 ID 类型，1：用户ID、2：部门ID、3：用户组ID
	RoleID    field.Int64  // 角色 ID
	DataID    field.Int64  // 数据 ID
	CreatedBy field.Int64  // 创建人
	CreatedAt field.Time   // 创建时间
	UpdatedBy field.Int64  // 更新人
	UpdatedAt field.Time   // 更新时间
	DeletedAt field.Field  // 删除时间
	TenantID  field.String // 租户 ID

	fieldMap map[string]field.Expr
}

func (s sysRoleIDScope) Table(newTableName string) *sysRoleIDScope {
	s.sysRoleIDScopeDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysRoleIDScope) As(alias string) *sysRoleIDScope {
	s.sysRoleIDScopeDo.DO = *(s.sysRoleIDScopeDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysRoleIDScope) updateTableName(table string) *sysRoleIDScope {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.Status = field.NewInt16(table, "status")
	s.Type = field.NewInt16(table, "type")
	s.RoleID = field.NewInt64(table, "role_id")
	s.DataID = field.NewInt64(table, "data_id")
	s.CreatedBy = field.NewInt64(table, "created_by")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedBy = field.NewInt64(table, "updated_by")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.DeletedAt = field.NewField(table, "deleted_at")
	s.TenantID = field.NewString(table, "tenant_id")

	s.fillFieldMap()

	return s
}

func (s *sysRoleIDScope) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysRoleIDScope) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 11)
	s.fieldMap["id"] = s.ID
	s.fieldMap["status"] = s.Status
	s.fieldMap["type"] = s.Type
	s.fieldMap["role_id"] = s.RoleID
	s.fieldMap["data_id"] = s.DataID
	s.fieldMap["created_by"] = s.CreatedBy
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_by"] = s.UpdatedBy
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["deleted_at"] = s.DeletedAt
	s.fieldMap["tenant_id"] = s.TenantID
}

func (s sysRoleIDScope) clone(db *gorm.DB) sysRoleIDScope {
	s.sysRoleIDScopeDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysRoleIDScope) replaceDB(db *gorm.DB) sysRoleIDScope {
	s.sysRoleIDScopeDo.ReplaceDB(db)
	return s
}

type sysRoleIDScopeDo struct{ gen.DO }

type ISysRoleIDScopeDo interface {
	gen.SubQuery
	Debug() ISysRoleIDScopeDo
	WithContext(ctx context.Context) ISysRoleIDScopeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysRoleIDScopeDo
	WriteDB() ISysRoleIDScopeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysRoleIDScopeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysRoleIDScopeDo
	Not(conds ...gen.Condition) ISysRoleIDScopeDo
	Or(conds ...gen.Condition) ISysRoleIDScopeDo
	Select(conds ...field.Expr) ISysRoleIDScopeDo
	Where(conds ...gen.Condition) ISysRoleIDScopeDo
	Order(conds ...field.Expr) ISysRoleIDScopeDo
	Distinct(cols ...field.Expr) ISysRoleIDScopeDo
	Omit(cols ...field.Expr) ISysRoleIDScopeDo
	Join(table schema.Tabler, on ...field.Expr) ISysRoleIDScopeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysRoleIDScopeDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysRoleIDScopeDo
	Group(cols ...field.Expr) ISysRoleIDScopeDo
	Having(conds ...gen.Condition) ISysRoleIDScopeDo
	Limit(limit int) ISysRoleIDScopeDo
	Offset(offset int) ISysRoleIDScopeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysRoleIDScopeDo
	Unscoped() ISysRoleIDScopeDo
	Create(values ...*model.SysRoleIDScope) error
	CreateInBatches(values []*model.SysRoleIDScope, batchSize int) error
	Save(values ...*model.SysRoleIDScope) error
	First() (*model.SysRoleIDScope, error)
	Take() (*model.SysRoleIDScope, error)
	Last() (*model.SysRoleIDScope, error)
	Find() ([]*model.SysRoleIDScope, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysRoleIDScope, err error)
	FindInBatches(result *[]*model.SysRoleIDScope, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SysRoleIDScope) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysRoleIDScopeDo
	Assign(attrs ...field.AssignExpr) ISysRoleIDScopeDo
	Joins(fields ...field.RelationField) ISysRoleIDScopeDo
	Preload(fields ...field.RelationField) ISysRoleIDScopeDo
	FirstOrInit() (*model.SysRoleIDScope, error)
	FirstOrCreate() (*model.SysRoleIDScope, error)
	FindByPage(offset int, limit int) (result []*model.SysRoleIDScope, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysRoleIDScopeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysRoleIDScopeDo) Debug() ISysRoleIDScopeDo {
	return s.withDO(s.DO.Debug())
}

func (s sysRoleIDScopeDo) WithContext(ctx context.Context) ISysRoleIDScopeDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysRoleIDScopeDo) ReadDB() ISysRoleIDScopeDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysRoleIDScopeDo) WriteDB() ISysRoleIDScopeDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysRoleIDScopeDo) Session(config *gorm.Session) ISysRoleIDScopeDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysRoleIDScopeDo) Clauses(conds ...clause.Expression) ISysRoleIDScopeDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysRoleIDScopeDo) Returning(value interface{}, columns ...string) ISysRoleIDScopeDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysRoleIDScopeDo) Not(conds ...gen.Condition) ISysRoleIDScopeDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysRoleIDScopeDo) Or(conds ...gen.Condition) ISysRoleIDScopeDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysRoleIDScopeDo) Select(conds ...field.Expr) ISysRoleIDScopeDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysRoleIDScopeDo) Where(conds ...gen.Condition) ISysRoleIDScopeDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysRoleIDScopeDo) Order(conds ...field.Expr) ISysRoleIDScopeDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysRoleIDScopeDo) Distinct(cols ...field.Expr) ISysRoleIDScopeDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysRoleIDScopeDo) Omit(cols ...field.Expr) ISysRoleIDScopeDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysRoleIDScopeDo) Join(table schema.Tabler, on ...field.Expr) ISysRoleIDScopeDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysRoleIDScopeDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysRoleIDScopeDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysRoleIDScopeDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysRoleIDScopeDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysRoleIDScopeDo) Group(cols ...field.Expr) ISysRoleIDScopeDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysRoleIDScopeDo) Having(conds ...gen.Condition) ISysRoleIDScopeDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysRoleIDScopeDo) Limit(limit int) ISysRoleIDScopeDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysRoleIDScopeDo) Offset(offset int) ISysRoleIDScopeDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysRoleIDScopeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysRoleIDScopeDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysRoleIDScopeDo) Unscoped() ISysRoleIDScopeDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysRoleIDScopeDo) Create(values ...*model.SysRoleIDScope) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysRoleIDScopeDo) CreateInBatches(values []*model.SysRoleIDScope, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysRoleIDScopeDo) Save(values ...*model.SysRoleIDScope) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysRoleIDScopeDo) First() (*model.SysRoleIDScope, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysRoleIDScope), nil
	}
}

func (s sysRoleIDScopeDo) Take() (*model.SysRoleIDScope, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysRoleIDScope), nil
	}
}

func (s sysRoleIDScopeDo) Last() (*model.SysRoleIDScope, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysRoleIDScope), nil
	}
}

func (s sysRoleIDScopeDo) Find() ([]*model.SysRoleIDScope, error) {
	result, err := s.DO.Find()
	return result.([]*model.SysRoleIDScope), err
}

func (s sysRoleIDScopeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysRoleIDScope, err error) {
	buf := make([]*model.SysRoleIDScope, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysRoleIDScopeDo) FindInBatches(result *[]*model.SysRoleIDScope, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysRoleIDScopeDo) Attrs(attrs ...field.AssignExpr) ISysRoleIDScopeDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysRoleIDScopeDo) Assign(attrs ...field.AssignExpr) ISysRoleIDScopeDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysRoleIDScopeDo) Joins(fields ...field.RelationField) ISysRoleIDScopeDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysRoleIDScopeDo) Preload(fields ...field.RelationField) ISysRoleIDScopeDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysRoleIDScopeDo) FirstOrInit() (*model.SysRoleIDScope, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysRoleIDScope), nil
	}
}

func (s sysRoleIDScopeDo) FirstOrCreate() (*model.SysRoleIDScope, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysRoleIDScope), nil
	}
}

func (s sysRoleIDScopeDo) FindByPage(offset int, limit int) (result []*model.SysRoleIDScope, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysRoleIDScopeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysRoleIDScopeDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysRoleIDScopeDo) Delete(models ...*model.SysRoleIDScope) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysRoleIDScopeDo) withDO(do gen.Dao) *sysRoleIDScopeDo {
	s.DO = *do.(*gen.DO)
	return s
}
