// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"go_orm_tt/internal/model"
)

func newSysDeptClosure(db *gorm.DB, opts ...gen.DOOption) sysDeptClosure {
	_sysDeptClosure := sysDeptClosure{}

	_sysDeptClosure.sysDeptClosureDo.UseDB(db, opts...)
	_sysDeptClosure.sysDeptClosureDo.UseModel(&model.SysDeptClosure{})

	tableName := _sysDeptClosure.sysDeptClosureDo.TableName()
	_sysDeptClosure.ALL = field.NewAsterisk(tableName)
	_sysDeptClosure.ID = field.NewInt64(tableName, "id")
	_sysDeptClosure.AncestorID = field.NewInt64(tableName, "ancestor_id")
	_sysDeptClosure.DescendantID = field.NewInt64(tableName, "descendant_id")
	_sysDeptClosure.Depth = field.NewInt32(tableName, "depth")

	_sysDeptClosure.fillFieldMap()

	return _sysDeptClosure
}

type sysDeptClosure struct {
	sysDeptClosureDo

	ALL          field.Asterisk
	ID           field.Int64
	AncestorID   field.Int64 // 祖先节点ID
	DescendantID field.Int64 // 后代节点ID
	Depth        field.Int32 // 深度/距离（0表示自身，1表示直接子节点，2表示孙子节点...）

	fieldMap map[string]field.Expr
}

func (s sysDeptClosure) Table(newTableName string) *sysDeptClosure {
	s.sysDeptClosureDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysDeptClosure) As(alias string) *sysDeptClosure {
	s.sysDeptClosureDo.DO = *(s.sysDeptClosureDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysDeptClosure) updateTableName(table string) *sysDeptClosure {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.AncestorID = field.NewInt64(table, "ancestor_id")
	s.DescendantID = field.NewInt64(table, "descendant_id")
	s.Depth = field.NewInt32(table, "depth")

	s.fillFieldMap()

	return s
}

func (s *sysDeptClosure) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysDeptClosure) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 4)
	s.fieldMap["id"] = s.ID
	s.fieldMap["ancestor_id"] = s.AncestorID
	s.fieldMap["descendant_id"] = s.DescendantID
	s.fieldMap["depth"] = s.Depth
}

func (s sysDeptClosure) clone(db *gorm.DB) sysDeptClosure {
	s.sysDeptClosureDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysDeptClosure) replaceDB(db *gorm.DB) sysDeptClosure {
	s.sysDeptClosureDo.ReplaceDB(db)
	return s
}

type sysDeptClosureDo struct{ gen.DO }

type ISysDeptClosureDo interface {
	gen.SubQuery
	Debug() ISysDeptClosureDo
	WithContext(ctx context.Context) ISysDeptClosureDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysDeptClosureDo
	WriteDB() ISysDeptClosureDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysDeptClosureDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysDeptClosureDo
	Not(conds ...gen.Condition) ISysDeptClosureDo
	Or(conds ...gen.Condition) ISysDeptClosureDo
	Select(conds ...field.Expr) ISysDeptClosureDo
	Where(conds ...gen.Condition) ISysDeptClosureDo
	Order(conds ...field.Expr) ISysDeptClosureDo
	Distinct(cols ...field.Expr) ISysDeptClosureDo
	Omit(cols ...field.Expr) ISysDeptClosureDo
	Join(table schema.Tabler, on ...field.Expr) ISysDeptClosureDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysDeptClosureDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysDeptClosureDo
	Group(cols ...field.Expr) ISysDeptClosureDo
	Having(conds ...gen.Condition) ISysDeptClosureDo
	Limit(limit int) ISysDeptClosureDo
	Offset(offset int) ISysDeptClosureDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysDeptClosureDo
	Unscoped() ISysDeptClosureDo
	Create(values ...*model.SysDeptClosure) error
	CreateInBatches(values []*model.SysDeptClosure, batchSize int) error
	Save(values ...*model.SysDeptClosure) error
	First() (*model.SysDeptClosure, error)
	Take() (*model.SysDeptClosure, error)
	Last() (*model.SysDeptClosure, error)
	Find() ([]*model.SysDeptClosure, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysDeptClosure, err error)
	FindInBatches(result *[]*model.SysDeptClosure, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SysDeptClosure) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysDeptClosureDo
	Assign(attrs ...field.AssignExpr) ISysDeptClosureDo
	Joins(fields ...field.RelationField) ISysDeptClosureDo
	Preload(fields ...field.RelationField) ISysDeptClosureDo
	FirstOrInit() (*model.SysDeptClosure, error)
	FirstOrCreate() (*model.SysDeptClosure, error)
	FindByPage(offset int, limit int) (result []*model.SysDeptClosure, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysDeptClosureDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysDeptClosureDo) Debug() ISysDeptClosureDo {
	return s.withDO(s.DO.Debug())
}

func (s sysDeptClosureDo) WithContext(ctx context.Context) ISysDeptClosureDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysDeptClosureDo) ReadDB() ISysDeptClosureDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysDeptClosureDo) WriteDB() ISysDeptClosureDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysDeptClosureDo) Session(config *gorm.Session) ISysDeptClosureDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysDeptClosureDo) Clauses(conds ...clause.Expression) ISysDeptClosureDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysDeptClosureDo) Returning(value interface{}, columns ...string) ISysDeptClosureDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysDeptClosureDo) Not(conds ...gen.Condition) ISysDeptClosureDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysDeptClosureDo) Or(conds ...gen.Condition) ISysDeptClosureDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysDeptClosureDo) Select(conds ...field.Expr) ISysDeptClosureDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysDeptClosureDo) Where(conds ...gen.Condition) ISysDeptClosureDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysDeptClosureDo) Order(conds ...field.Expr) ISysDeptClosureDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysDeptClosureDo) Distinct(cols ...field.Expr) ISysDeptClosureDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysDeptClosureDo) Omit(cols ...field.Expr) ISysDeptClosureDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysDeptClosureDo) Join(table schema.Tabler, on ...field.Expr) ISysDeptClosureDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysDeptClosureDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysDeptClosureDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysDeptClosureDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysDeptClosureDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysDeptClosureDo) Group(cols ...field.Expr) ISysDeptClosureDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysDeptClosureDo) Having(conds ...gen.Condition) ISysDeptClosureDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysDeptClosureDo) Limit(limit int) ISysDeptClosureDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysDeptClosureDo) Offset(offset int) ISysDeptClosureDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysDeptClosureDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysDeptClosureDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysDeptClosureDo) Unscoped() ISysDeptClosureDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysDeptClosureDo) Create(values ...*model.SysDeptClosure) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysDeptClosureDo) CreateInBatches(values []*model.SysDeptClosure, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysDeptClosureDo) Save(values ...*model.SysDeptClosure) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysDeptClosureDo) First() (*model.SysDeptClosure, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysDeptClosure), nil
	}
}

func (s sysDeptClosureDo) Take() (*model.SysDeptClosure, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysDeptClosure), nil
	}
}

func (s sysDeptClosureDo) Last() (*model.SysDeptClosure, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysDeptClosure), nil
	}
}

func (s sysDeptClosureDo) Find() ([]*model.SysDeptClosure, error) {
	result, err := s.DO.Find()
	return result.([]*model.SysDeptClosure), err
}

func (s sysDeptClosureDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysDeptClosure, err error) {
	buf := make([]*model.SysDeptClosure, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysDeptClosureDo) FindInBatches(result *[]*model.SysDeptClosure, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysDeptClosureDo) Attrs(attrs ...field.AssignExpr) ISysDeptClosureDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysDeptClosureDo) Assign(attrs ...field.AssignExpr) ISysDeptClosureDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysDeptClosureDo) Joins(fields ...field.RelationField) ISysDeptClosureDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysDeptClosureDo) Preload(fields ...field.RelationField) ISysDeptClosureDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysDeptClosureDo) FirstOrInit() (*model.SysDeptClosure, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysDeptClosure), nil
	}
}

func (s sysDeptClosureDo) FirstOrCreate() (*model.SysDeptClosure, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysDeptClosure), nil
	}
}

func (s sysDeptClosureDo) FindByPage(offset int, limit int) (result []*model.SysDeptClosure, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysDeptClosureDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysDeptClosureDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysDeptClosureDo) Delete(models ...*model.SysDeptClosure) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysDeptClosureDo) withDO(do gen.Dao) *sysDeptClosureDo {
	s.DO = *do.(*gen.DO)
	return s
}
