// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"go_orm_tt/internal/model"
)

func newSysUserGroupMapping(db *gorm.DB, opts ...gen.DOOption) sysUserGroupMapping {
	_sysUserGroupMapping := sysUserGroupMapping{}

	_sysUserGroupMapping.sysUserGroupMappingDo.UseDB(db, opts...)
	_sysUserGroupMapping.sysUserGroupMappingDo.UseModel(&model.SysUserGroupMapping{})

	tableName := _sysUserGroupMapping.sysUserGroupMappingDo.TableName()
	_sysUserGroupMapping.ALL = field.NewAsterisk(tableName)
	_sysUserGroupMapping.GroupID = field.NewInt64(tableName, "group_id")
	_sysUserGroupMapping.UserID = field.NewInt64(tableName, "user_id")

	_sysUserGroupMapping.fillFieldMap()

	return _sysUserGroupMapping
}

type sysUserGroupMapping struct {
	sysUserGroupMappingDo

	ALL     field.Asterisk
	GroupID field.Int64 // 用户组 ID
	UserID  field.Int64 // 用户 ID

	fieldMap map[string]field.Expr
}

func (s sysUserGroupMapping) Table(newTableName string) *sysUserGroupMapping {
	s.sysUserGroupMappingDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysUserGroupMapping) As(alias string) *sysUserGroupMapping {
	s.sysUserGroupMappingDo.DO = *(s.sysUserGroupMappingDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysUserGroupMapping) updateTableName(table string) *sysUserGroupMapping {
	s.ALL = field.NewAsterisk(table)
	s.GroupID = field.NewInt64(table, "group_id")
	s.UserID = field.NewInt64(table, "user_id")

	s.fillFieldMap()

	return s
}

func (s *sysUserGroupMapping) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysUserGroupMapping) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 2)
	s.fieldMap["group_id"] = s.GroupID
	s.fieldMap["user_id"] = s.UserID
}

func (s sysUserGroupMapping) clone(db *gorm.DB) sysUserGroupMapping {
	s.sysUserGroupMappingDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysUserGroupMapping) replaceDB(db *gorm.DB) sysUserGroupMapping {
	s.sysUserGroupMappingDo.ReplaceDB(db)
	return s
}

type sysUserGroupMappingDo struct{ gen.DO }

type ISysUserGroupMappingDo interface {
	gen.SubQuery
	Debug() ISysUserGroupMappingDo
	WithContext(ctx context.Context) ISysUserGroupMappingDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysUserGroupMappingDo
	WriteDB() ISysUserGroupMappingDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysUserGroupMappingDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysUserGroupMappingDo
	Not(conds ...gen.Condition) ISysUserGroupMappingDo
	Or(conds ...gen.Condition) ISysUserGroupMappingDo
	Select(conds ...field.Expr) ISysUserGroupMappingDo
	Where(conds ...gen.Condition) ISysUserGroupMappingDo
	Order(conds ...field.Expr) ISysUserGroupMappingDo
	Distinct(cols ...field.Expr) ISysUserGroupMappingDo
	Omit(cols ...field.Expr) ISysUserGroupMappingDo
	Join(table schema.Tabler, on ...field.Expr) ISysUserGroupMappingDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysUserGroupMappingDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysUserGroupMappingDo
	Group(cols ...field.Expr) ISysUserGroupMappingDo
	Having(conds ...gen.Condition) ISysUserGroupMappingDo
	Limit(limit int) ISysUserGroupMappingDo
	Offset(offset int) ISysUserGroupMappingDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysUserGroupMappingDo
	Unscoped() ISysUserGroupMappingDo
	Create(values ...*model.SysUserGroupMapping) error
	CreateInBatches(values []*model.SysUserGroupMapping, batchSize int) error
	Save(values ...*model.SysUserGroupMapping) error
	First() (*model.SysUserGroupMapping, error)
	Take() (*model.SysUserGroupMapping, error)
	Last() (*model.SysUserGroupMapping, error)
	Find() ([]*model.SysUserGroupMapping, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysUserGroupMapping, err error)
	FindInBatches(result *[]*model.SysUserGroupMapping, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SysUserGroupMapping) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysUserGroupMappingDo
	Assign(attrs ...field.AssignExpr) ISysUserGroupMappingDo
	Joins(fields ...field.RelationField) ISysUserGroupMappingDo
	Preload(fields ...field.RelationField) ISysUserGroupMappingDo
	FirstOrInit() (*model.SysUserGroupMapping, error)
	FirstOrCreate() (*model.SysUserGroupMapping, error)
	FindByPage(offset int, limit int) (result []*model.SysUserGroupMapping, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysUserGroupMappingDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysUserGroupMappingDo) Debug() ISysUserGroupMappingDo {
	return s.withDO(s.DO.Debug())
}

func (s sysUserGroupMappingDo) WithContext(ctx context.Context) ISysUserGroupMappingDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysUserGroupMappingDo) ReadDB() ISysUserGroupMappingDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysUserGroupMappingDo) WriteDB() ISysUserGroupMappingDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysUserGroupMappingDo) Session(config *gorm.Session) ISysUserGroupMappingDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysUserGroupMappingDo) Clauses(conds ...clause.Expression) ISysUserGroupMappingDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysUserGroupMappingDo) Returning(value interface{}, columns ...string) ISysUserGroupMappingDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysUserGroupMappingDo) Not(conds ...gen.Condition) ISysUserGroupMappingDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysUserGroupMappingDo) Or(conds ...gen.Condition) ISysUserGroupMappingDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysUserGroupMappingDo) Select(conds ...field.Expr) ISysUserGroupMappingDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysUserGroupMappingDo) Where(conds ...gen.Condition) ISysUserGroupMappingDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysUserGroupMappingDo) Order(conds ...field.Expr) ISysUserGroupMappingDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysUserGroupMappingDo) Distinct(cols ...field.Expr) ISysUserGroupMappingDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysUserGroupMappingDo) Omit(cols ...field.Expr) ISysUserGroupMappingDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysUserGroupMappingDo) Join(table schema.Tabler, on ...field.Expr) ISysUserGroupMappingDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysUserGroupMappingDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysUserGroupMappingDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysUserGroupMappingDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysUserGroupMappingDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysUserGroupMappingDo) Group(cols ...field.Expr) ISysUserGroupMappingDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysUserGroupMappingDo) Having(conds ...gen.Condition) ISysUserGroupMappingDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysUserGroupMappingDo) Limit(limit int) ISysUserGroupMappingDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysUserGroupMappingDo) Offset(offset int) ISysUserGroupMappingDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysUserGroupMappingDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysUserGroupMappingDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysUserGroupMappingDo) Unscoped() ISysUserGroupMappingDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysUserGroupMappingDo) Create(values ...*model.SysUserGroupMapping) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysUserGroupMappingDo) CreateInBatches(values []*model.SysUserGroupMapping, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysUserGroupMappingDo) Save(values ...*model.SysUserGroupMapping) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysUserGroupMappingDo) First() (*model.SysUserGroupMapping, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysUserGroupMapping), nil
	}
}

func (s sysUserGroupMappingDo) Take() (*model.SysUserGroupMapping, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysUserGroupMapping), nil
	}
}

func (s sysUserGroupMappingDo) Last() (*model.SysUserGroupMapping, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysUserGroupMapping), nil
	}
}

func (s sysUserGroupMappingDo) Find() ([]*model.SysUserGroupMapping, error) {
	result, err := s.DO.Find()
	return result.([]*model.SysUserGroupMapping), err
}

func (s sysUserGroupMappingDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysUserGroupMapping, err error) {
	buf := make([]*model.SysUserGroupMapping, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysUserGroupMappingDo) FindInBatches(result *[]*model.SysUserGroupMapping, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysUserGroupMappingDo) Attrs(attrs ...field.AssignExpr) ISysUserGroupMappingDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysUserGroupMappingDo) Assign(attrs ...field.AssignExpr) ISysUserGroupMappingDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysUserGroupMappingDo) Joins(fields ...field.RelationField) ISysUserGroupMappingDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysUserGroupMappingDo) Preload(fields ...field.RelationField) ISysUserGroupMappingDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysUserGroupMappingDo) FirstOrInit() (*model.SysUserGroupMapping, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysUserGroupMapping), nil
	}
}

func (s sysUserGroupMappingDo) FirstOrCreate() (*model.SysUserGroupMapping, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysUserGroupMapping), nil
	}
}

func (s sysUserGroupMappingDo) FindByPage(offset int, limit int) (result []*model.SysUserGroupMapping, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysUserGroupMappingDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysUserGroupMappingDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysUserGroupMappingDo) Delete(models ...*model.SysUserGroupMapping) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysUserGroupMappingDo) withDO(do gen.Dao) *sysUserGroupMappingDo {
	s.DO = *do.(*gen.DO)
	return s
}
